import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource-variable/exo-2';
import localfont from "next/font/local"
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
const expo = localfont({
  src:[{
    path:"@/components/fonts/Expo-light.ttf",
    weight:"400"
  }],
  variable:"--expo-light"
})
export const metadata = {
  title: "MyzMary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl" className={`${expo.variable} scroll-smooth`}>
      <body className='font-Expo '>
        <div className="flex flex-col min-h-screen ">
        <header>
       
          
       <Navbar/>
      
      
         </header>
        <main className="flex-grow ">

        {children}
        </main>
        <footer>
          <Footer/>
        </footer>
        </div>

        
        </body>
    </html>
  );
}
