import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource-variable/exo-2';

import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyzMary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl" className="scroll-smooth">
      <body className=' '>
        <div className="flex flex-col min-h-screen ">
        <header>
       
          
       <Navbar/>
      
      
         </header>
        <main className="flex-grow ">

        {children}
        </main>
        <footer>
          <Footer/>
        </footer>
        </div>

        
        </body>
    </html>
  );
}
